### ISSUE TITLE
using more ways to take a screenshot.

### ISSUE THREAD

**Issue by uomar8** [firemaples/EverTranslator#332]
the app is using MediaProjection to take a screenshot and the [code ](https://github.com/firemaples/EverTranslator/blob/master/main/src/main/java/tw/firemaples/onscreenocr/screenshot/ScreenExtractor.kt)is good, but it could face some problems on some devices like this [error](https://github.com/firemaples/EverTranslator/issues/267#issue-1619727239)

there is another way called PixelCopy  but the problem is it only works on android 8 and above.

what I would like to suggest is to use both ways less than android 8 MediaProjection and 8 and above PixelCopy  

or we could use this library it will do the same.
https://github.com/bolteu/screenshotty/tree/master

also, i think it should be a beta test before it will released.

**Comment by firemaples** [comment]
Thanks for the suggestion. 

Looks like PixelCopy only works when you take a screenshot of the app itself because PixelCopy needs the reference of the target view.

Another way:
- [AccessibilityService#takeScreenshot](https://developer.android.com/reference/android/accessibilityservice/AccessibilityService#takeScreenshot(int,%20java.util.concurrent.Executor,%20android.accessibilityservice.AccessibilityService.TakeScreenshotCallback))
- Listen to screenshot folder and let user does the screenshot?

Let me check if there are other ways to take a screenshot on any app.
