### ISSUE TITLE
Shortcut to reverse the ordering of the texts

### ISSUE THREAD

**Issue by firemaples** [firemaples/EverTranslator#336]
For those languages can be written from right to left.

**Comment by uomar8** [comment]
The order of the text is right 😅 I don't think this button is useful

What's wrong is (Text alignment) and it's part of the UI
![images (5)](https://github.com/firemaples/EverTranslator/assets/7046347/26fc0d1c-ae50-4972-91a7-f8ac5ba8c9b5)


This is now
![Screenshot_20231015_155138_com huawei android launcher_edit_365269325985](https://github.com/firemaples/EverTranslator/assets/7046347/c55ae57f-fca8-47b7-aebe-512fbfa4c6da)


And this is how it should look like
![ydydyduf (20231015035934)](https://github.com/firemaples/EverTranslator/assets/7046347/5a0c98e5-0fb5-43ee-a187-2be1d0e5ec19)

And we stopped RTL from the layout because it made a lot of problems [Here](https://github.com/firemaples/EverTranslator/pull/250)

**Comment by firemaples** [comment]
Oh, for the RTL layout issue... 🤔
I'm thinking about restarting the refactoring of this project to full MVVM + DI + Jetpack compose then some UI issues should be fixed at the same time.
It can make the code more understandable and easier to maintain.

**Comment by uomar8** [comment]
> Oh, for the RTL layout issue... 🤔 I'm thinking about restarting the refactoring of this project to full MVVM + DI + Jetpack compose then some UI issues should be fixed at the same time. It can make the code more understandable and easier to maintain.

I think this is a great idea, and thank you for your great work
